<?php
$galleryClasses = [];
$galleryClasses[] = 'gallery-placeholder ox-gallery';
$theme_settings = $this->helper('Olegnax\Athlete2\Helper\Helper')->getConfig('athlete2_settings');
$productImageWidth = $theme_settings['product_images']['product_image_width'] ?: $block->getImageAttribute('product_page_image_medium', 'width');
$productImageHeight = $theme_settings['product_images']['product_image_height'] ?: $block->getImageAttribute('product_page_image_medium', 'height');
$imageRatio = $productImageHeight/$productImageWidth*100 . '%';
$popupEnabled = $theme_settings['product']['gallery_popup'];
$stickyEnabled = $theme_settings['product']['gallery_sticky'];
$galleryColumns = $theme_settings['product']['gallery_layout'];
$imagesMinCount = $theme_settings['product']['gallery_images_min_count'];
$zoomCursor = $theme_settings['product']['gallery_zoom_cursor'];
$imageStretch = $theme_settings['product']['gallery_images_stretch'];
$lazy = $theme_settings['general']['lazyload'] && ! $theme_settings['product']['gallery_disable_lazy'];
$galleryImages = $this->getGalleryImages();
$imagesCount = count($galleryImages);
$helper = $block->getData('imageHelper');
if ($imagesCount < $imagesMinCount) {
    $galleryClasses[] = 'gallery--1col';
} else {
    $galleryClasses[] = 'gallery--' . $galleryColumns;
}
if ($imagesCount <= 1) {
    $galleryClasses[] = 'single-image';
}
if ($popupEnabled){
    $galleryClasses[] = 'gallery--with-popup';
}
if (true){
    $galleryClasses[] = 'gallery--with-replace';
}
$imageWrapperStyles ='';
if ($imageStretch == 'stretch' || $imageStretch == 'center'){
    $galleryClasses[] = 'gallery--' . $imageStretch . '-images';
	$imageWrapperStyles = ' style="padding-bottom: ' . $imageRatio . '"';
}
if($zoomCursor){
	$galleryClasses[] = 'ox-custom-cursor';
}
$index = 0;
?>

<div class="<?= implode(' ', $galleryClasses) ?>" data-gallery-role="gallery-placeholder">
    <?php if ($zoomCursor): ?>
		<div id="ox-zoom-cursor"><span></span></div>
    <?php endif; ?>
    <?php if (!empty($galleryImages)): ?>
        <?php $imageAlt = $block->getProduct()->getName(); ?>
        <?php foreach ($galleryImages as $image): ?>
			<div class="gallery__item">
                <?php if ($popupEnabled): ?>
                    <?php if ($image->getMediaType() != 'external-video'): ?>
							<div class="gallery__image-wrapper"<?= $imageWrapperStyles ?>>
								<?php if ($lazy) : ?>
									<img class="gallery__image lazy"
										 width="<?= $productImageWidth ?>" height="<?= $productImageHeight ?>"
										 src="<?= $this->getViewFileUrl('Olegnax_Core/images/preloader-img.svg'); ?>"
										 data-preloader="<?= $this->getViewFileUrl('Olegnax_Core/images/preloader-img.svg'); ?>"
										 data-original="<?= $block->escapeUrl($image->getMediumImageUrl()) ?>"
										 data-full="<?= $block->escapeUrl($image->getLargeImageUrl()) ?>"
										 data-ox="gallery_product"
										 data-index="<?= $index++; ?>"
										 alt="<?php echo $imageAlt ?>"/>
								<?php else : ?>
									<img class="gallery__image"
										 src="<?php echo $image->getMediumImageUrl(); ?>"
										 data-full="<?= $block->escapeUrl($image->getLargeImageUrl()) ?>"
										 data-ox="gallery_product"
										 data-index="<?= $index++; ?>"
										 alt="<?php echo $imageAlt ?>"
									/>
								<?php endif; ?>
							</div>
                    <?php else: ?>
							<div class="gallery__image-wrapper"<?= $imageWrapperStyles ?>>
								<?php if ($lazy) : ?>
									<img class="gallery__image lazy"
										 width="<?= $productImageWidth ?>" height="<?= $productImageHeight ?>"
										 src="<?= $this->getViewFileUrl('Olegnax_Core/images/preloader-img.svg'); ?>"
										 data-preloader="<?= $this->getViewFileUrl('Olegnax_Core/images/preloader-img.svg'); ?>"
										 data-original="<?= $block->escapeUrl($image->getMediumImageUrl()) ?>"
										 data-full="<?= $block->escapeUrl($image->getVideoUrl()) ?>"
										 data-type="video"
										 data-ox="gallery_product"
										 data-index="<?= $index++; ?>"
										 alt="<?php echo $imageAlt ?>"/>
								<?php else : ?>
									<img class="gallery__image"
										 src="<?php echo $image->getMediumImageUrl(); ?>"
										 data-full="<?= $block->escapeUrl($image->getVideoUrl()) ?>"
										 data-type="video"
										 data-ox="gallery_product"
										 data-index="<?= $index++; ?>"
										 alt="<?php echo $imageAlt ?>"/>
								<?php endif; ?>
							</div>
                    <?php endif ?>
                <?php else: ?>
                    <?php if ($image->getMediaType() != 'external-video'): ?>
						<div class="gallery__image-wrapper"<?= $imageWrapperStyles ?>>
							<?php if ($lazy) : ?>
								<img class="gallery__image lazy"
									 width="<?= $productImageWidth ?>" height="<?= $productImageHeight ?>"
									 src="<?= $this->getViewFileUrl('Olegnax_Core/images/preloader-img.svg'); ?>"
									 data-preloader="<?= $this->getViewFileUrl('Olegnax_Core/images/preloader-img.svg'); ?>"
									 data-original="<?= $block->escapeUrl($image->getMediumImageUrl()) ?>"
									 data-ox="gallery_product"
									 alt="<?php echo $imageAlt ?>"/>
							<?php else : ?>
								<img class="gallery__image" src="<?php echo $image->getMediumImageUrl(); ?>"
									 data-ox="gallery_product" alt="<?php echo $imageAlt ?>"/>
							<?php endif; ?>
						</div>
                    <?php else: ?>
						<iframe width="<?= $productImageWidth ?>" height="<?= $productImageHeight ?>" src="<?= $image->getVideoUrl(); ?>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                    <?php endif ?>
                <?php endif ?>
			</div>
        <?php endforeach ?>
    <?php else: ?>
        <?= $helper->getDefaultPlaceholderUrl('image'); ?>
    <?php endif; ?>
</div>
<script type="text/x-magento-init">
    {
		<?php if ( $stickyEnabled ) : ?>
			"*": {
				"sticky-sidebar": {
					"wrapper": ".athlete2_product_info__wrapper",
					"sticky": ".product-info-main, .product.media"
				}
			},
		<?php endif; ?>
        ".gallery--with-popup[data-gallery-role=gallery-placeholder]": {
            "photoswipe-init": {
            	"itemSelector": ".gallery__item .gallery__image[data-full]",
            	"defaultVideoSize": "<?= $productImageWidth . 'x' . $productImageHeight ?>"
            }
        }

    }
</script>